<?php
declare(strict_types=1);
require_once __DIR__ . '/Test.php';
require_once __DIR__ . '/../src/Router.php';
same(true, class_exists(Finados\VoceroPasswordReset::class));

$resetRoot = tempnam(sys_get_temp_dir(), 'finados-reset-');
unlink($resetRoot); mkdir($resetRoot, 0700);
register_shutdown_function(static function () use ($resetRoot): void {
    $entries = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($resetRoot, FilesystemIterator::SKIP_DOTS), RecursiveIteratorIterator::CHILD_FIRST);
    foreach ($entries as $entry) $entry->isDir() ? rmdir($entry->getPathname()) : unlink($entry->getPathname());
    rmdir($resetRoot);
});
$resetConfigPath = $resetRoot . '/config.json';
file_put_contents($resetConfigPath, json_encode([
    'environment' => 'test', 'databaseDsn' => 'sqlite::memory:', 'databaseUser' => '', 'databasePassword' => '',
    'allowedOrigin' => 'https://complejomushucruna.com', 'encryptionKey' => base64_encode(str_repeat('e', 32)), 'hmacKey' => base64_encode(str_repeat('h', 32)),
]));
$resetConfig = Finados\Config::fromFile($resetConfigPath);
$resetDb = Finados\Database::connect($resetConfig);
foreach (['001_initial', '002_sheets_outbox', '003_vocero_accounts'] as $migration) $resetDb->exec(file_get_contents(__DIR__ . '/../migrations/' . $migration . '_sqlite.sql'));
$resetCrypto = new Finados\Crypto($resetConfig);
$resetRepository = new Finados\VocerosRepository($resetDb, $resetCrypto);
$resetNow = time();
$resetClock = static function () use (&$resetNow): int { return $resetNow; };
$resetAuth = new Finados\VoceroAuth($resetDb, $resetConfig, $resetClock);
$resetService = new Finados\VoceroPasswordReset($resetDb, $resetConfig, $resetClock);
$resetOldPassword = bin2hex(random_bytes(12)); $resetNewPassword = bin2hex(random_bytes(12));
$resetAuth->register('reset@example.invalid', $resetOldPassword, true, '192.0.2.10');
$resetDb->prepare('INSERT INTO admin_users (public_id, username, password_hash, created_at, updated_at) VALUES (?, ?, ?, ?, ?)')->execute([str_repeat('a', 32), 'admin', Finados\Auth::hashPassword($resetOldPassword), gmdate('Y-m-d H:i:s'), gmdate('Y-m-d H:i:s')]);
$resetRecord = ['submission_id' => str_repeat('b', 32), 'full_name' => 'Persona sintética', 'cedula' => '1800000001', 'birth_date' => '2000-01-02', 'age_at_submission' => 26, 'whatsapp' => '+593990000001', 'email' => 'reset@example.invalid', 'city' => 'Prueba', 'main_network' => 'TikTok', 'previous_participation' => 'No', 'community_source' => 'Prueba', 'kit_pickup' => 'Sí', 'submitted_at' => gmdate('Y-m-d H:i:s')];
$resetConsents = array_map(static fn ($type) => ['consent_type' => $type, 'accepted' => 1, 'text_version' => 'test', 'text_hash' => hash('sha256', $type), 'accepted_at' => gmdate('Y-m-d H:i:s'), 'ip' => '192.0.2.10', 'user_agent' => 'Synthetic', 'source_url' => 'https://example.invalid/', 'method' => 'checkbox'], ['privacy', 'image', 'data']);
$resetId = $resetRepository->create($resetRecord, $resetConsents);
$resetHistorical = $resetRepository->create(array_replace($resetRecord, ['submission_id' => str_repeat('c', 32)]), $resetConsents);
$resetDb->exec("INSERT INTO vocero_account_links (account_id,vocero_id,created_at) VALUES (1,1,CURRENT_TIMESTAMP)");
throws(fn () => $resetService->create($resetHistorical, 1, '192.0.2.10'), OutOfBoundsException::class);
throws(fn () => $resetService->create('../config', 1, '192.0.2.10'), InvalidArgumentException::class);
throws(fn () => $resetService->create($resetId, 999, '192.0.2.10'), Finados\Forbidden::class);
$resetDb->exec('UPDATE admin_users SET active = 0');
throws(fn () => $resetService->create($resetId, 1, '192.0.2.10'), Finados\Forbidden::class);
$resetDb->exec('UPDATE admin_users SET active = 1');
$resetDb->exec('UPDATE vocero_accounts SET active = 0');
throws(fn () => $resetService->create($resetId, 1, '192.0.2.10'), OutOfBoundsException::class);
$resetDb->exec('UPDATE vocero_accounts SET active = 1');

$resetFirst = $resetService->create($resetId, 1, '192.0.2.10');
same(1, preg_match('/^[a-f0-9]{64}$/D', $resetFirst));
$resetRow = $resetDb->query('SELECT * FROM vocero_password_resets')->fetch();
same(hash_hmac('sha256', $resetFirst, str_repeat('h', 32)), $resetRow['token_hash']);
same(gmdate('Y-m-d H:i:s', $resetNow + 1800), $resetRow['expires_at']);
same(false, str_contains(json_encode($resetRow), $resetFirst));
$resetSecond = $resetService->create($resetId, 1, '192.0.2.10');
same(false, $resetFirst === $resetSecond);
throws(fn () => $resetService->consume($resetFirst, $resetNewPassword, '192.0.2.11'), InvalidArgumentException::class);
foreach ([str_repeat('x', 9), str_repeat('x', 129), "bad\xffpassword"] as $invalid) throws(fn () => $resetService->consume($resetSecond, $invalid, '192.0.2.11'), InvalidArgumentException::class);

// Failed audit must roll back both invalidation of the previous token and new issuance.
$resetDb->exec("CREATE TRIGGER reset_audit_fail BEFORE INSERT ON audit_log WHEN NEW.event_type = 'vocero.password_reset_created' BEGIN SELECT RAISE(ABORT, 'synthetic audit failure'); END");
throws(fn () => $resetService->create($resetId, 1, '192.0.2.10'), Throwable::class);
same(2, (int) $resetDb->query('SELECT COUNT(*) FROM vocero_password_resets')->fetchColumn());
same(null, $resetDb->query('SELECT consumed_at FROM vocero_password_resets ORDER BY id DESC LIMIT 1')->fetchColumn());
$resetDb->exec('DROP TRIGGER reset_audit_fail');
$resetAuth->login('reset@example.invalid', $resetOldPassword, '192.0.2.12');
$resetOldSession = $_SESSION;
$resetDb->exec("CREATE TRIGGER reset_audit_fail BEFORE INSERT ON audit_log WHEN NEW.event_type = 'vocero.password_reset_consumed' BEGIN SELECT RAISE(ABORT, 'synthetic audit failure'); END");
throws(fn () => $resetService->consume($resetSecond, $resetNewPassword, '192.0.2.13'), Throwable::class);
same(true, password_verify($resetOldPassword, $resetDb->query('SELECT password_hash FROM vocero_accounts')->fetchColumn()));
same(null, $resetDb->query('SELECT consumed_at FROM vocero_password_resets ORDER BY id DESC LIMIT 1')->fetchColumn());
$resetDb->exec('DROP TRIGGER reset_audit_fail');
$resetNow += 1799;
$resetService->consume($resetSecond, $resetNewPassword, '192.0.2.14');
same(true, password_verify($resetNewPassword, $resetDb->query('SELECT password_hash FROM vocero_accounts')->fetchColumn()));
$_SESSION = $resetOldSession;
throws(fn () => $resetAuth->requireUser(), Finados\Unauthorized::class);
throws(fn () => $resetService->consume($resetSecond, $resetOldPassword, '192.0.2.15'), InvalidArgumentException::class);
$resetThird = $resetService->create($resetId, 1, '192.0.2.10');
$resetNow += 1800;
throws(fn () => $resetService->consume($resetThird, $resetOldPassword, '192.0.2.16'), InvalidArgumentException::class);
$resetNow = time();
$resetValid = $resetService->create($resetId, 1, '192.0.2.10');
$resetDb->exec('UPDATE vocero_accounts SET active = 0');
throws(fn () => $resetService->consume($resetValid, $resetNewPassword, '192.0.2.17'), InvalidArgumentException::class);
$resetDb->exec('UPDATE vocero_accounts SET active = 1');
for ($i = 0; $i < 10; $i++) throws(fn () => $resetService->consume(str_repeat('0', 64), $resetNewPassword, '192.0.2.90'), InvalidArgumentException::class);
throws(fn () => $resetService->consume($resetValid, $resetNewPassword, '192.0.2.90'), Finados\PasswordResetRateLimit::class);
$resetAudit = json_encode($resetDb->query('SELECT * FROM audit_log')->fetchAll());
foreach ([$resetFirst, $resetSecond, $resetThird, $resetValid, $resetRow['token_hash'], $resetNewPassword] as $sensitive) same(false, str_contains($resetAudit, $sensitive));

// Real router, sessions and encrypted photo; no service methods are mocked.
Finados\Http::destroySession(); session_id(''); $_SESSION = [];
$resetRouter = new Finados\Router($resetConfig, $resetDb);
$resetServer = ['HTTP_ORIGIN' => $resetConfig->allowedOrigin(), 'CONTENT_TYPE' => 'application/json', 'REMOTE_ADDR' => '192.0.2.30'];
$resetSession = json_decode($resetRouter->handle('GET', '/api/vocero/auth/session', $resetServer)->body, true);
$resetServer['HTTP_X_CSRF_TOKEN'] = $resetSession['csrf'];
$resetBody = json_encode(['token' => $resetValid, 'password' => $resetNewPassword]);
same(403, $resetRouter->handle('POST', '/api/vocero/auth/reset', array_diff_key($resetServer, ['HTTP_ORIGIN' => 1]), $resetBody)->status);
same(403, $resetRouter->handle('POST', '/api/vocero/auth/reset', array_replace($resetServer, ['HTTP_X_CSRF_TOKEN' => 'wrong']), $resetBody)->status);
same(403, $resetRouter->handle('POST', '/api/vocero/auth/reset', array_replace($resetServer, ['REMOTE_ADDR' => 'bad']), $resetBody)->status);
same(200, $resetRouter->handle('POST', '/api/vocero/auth/reset', $resetServer, $resetBody)->status);
$resetSession = json_decode($resetRouter->handle('GET', '/api/vocero/auth/session', $resetServer)->body, true);
same(false, $resetSession['authenticated']);
$resetServer['HTTP_X_CSRF_TOKEN'] = $resetSession['csrf'];
$resetUsedResponse = $resetRouter->handle('POST', '/api/vocero/auth/reset', $resetServer, $resetBody);
$resetMissingResponse = $resetRouter->handle('POST', '/api/vocero/auth/reset', $resetServer, json_encode(['token' => str_repeat('0', 64), 'password' => $resetNewPassword]));
same(422, $resetUsedResponse->status); same($resetUsedResponse->body, $resetMissingResponse->body);
Finados\Http::destroySession(); session_id(''); $_SESSION = [];
$resetAdmin = new Finados\Auth($resetDb, $resetConfig);
$resetAdminLogin = $resetAdmin->login('admin', $resetOldPassword, '192.0.2.30');
$resetServer['HTTP_X_CSRF_TOKEN'] = $resetAdminLogin['csrf'];
same(403, $resetRouter->handle('POST', '/api/voceros/' . $resetId . '/password-reset', array_diff_key($resetServer, ['HTTP_ORIGIN' => 1]), '{}')->status);
$resetNow += 901; // Issuance quota from earlier service calls is already at its boundary in wall-clock tests.
$resetDb->exec("UPDATE vocero_password_resets SET created_at = '2020-01-01 00:00:00'");
$resetIssued = $resetRouter->handle('POST', '/api/voceros/' . $resetId . '/password-reset', $resetServer, '{}');
same(201, $resetIssued->status);
same(true, str_starts_with(json_decode($resetIssued->body, true)['resetUrl'], 'https://complejomushucruna.com/finados/voceros/restablecer/?token='));
for ($i = 0; $i < 4; $i++) same(201, $resetRouter->handle('POST', '/api/voceros/' . $resetId . '/password-reset', $resetServer, '{}')->status);
same(429, $resetRouter->handle('POST', '/api/voceros/' . $resetId . '/password-reset', $resetServer, '{}')->status);
$resetDetail = json_decode($resetRouter->handle('GET', '/api/voceros/' . $resetHistorical, $resetServer)->body, true);
same(false, $resetDetail['photo']['available']); same(false, $resetDetail['account']['active']);
same(404, $resetRouter->handle('GET', '/api/voceros/' . $resetHistorical . '/photo', $resetServer)->status);
$resetImagePath = $resetRoot . '/fixture.jpg'; $resetImage = imagecreatetruecolor(80, 100); imagejpeg($resetImage, $resetImagePath);
$resetStorage = new Finados\PhotoStorage($resetConfig, $resetCrypto);
$resetPhoto = $resetStorage->stage($resetImagePath, filesize($resetImagePath)); $resetStorage->promote($resetPhoto);
$resetDb->prepare('INSERT INTO vocero_photos (vocero_id, storage_key, content_type, bytes, sha256, width, height, created_at) VALUES (1,?,?,?,?,?,?,?)')->execute([$resetPhoto['storage_key'], 'image/jpeg', $resetPhoto['bytes'], $resetPhoto['sha256'], 80, 100, gmdate('Y-m-d H:i:s')]);
$resetPhotoResponse = $resetRouter->handle('GET', '/api/voceros/' . $resetId . '/photo', $resetServer);
same(200, $resetPhotoResponse->status); same('image/jpeg', $resetPhotoResponse->headers['Content-Type']); same('private, no-store', $resetPhotoResponse->headers['Cache-Control']); same('nosniff', $resetPhotoResponse->headers['X-Content-Type-Options']);
$resetDetail = json_decode($resetRouter->handle('GET', '/api/voceros/' . $resetId, $resetServer)->body, true);
same(true, $resetDetail['photo']['available']); same(true, $resetDetail['account']['active']);
same(false, str_contains(json_encode($resetDetail), $resetPhoto['storage_key']));
same(false, str_contains(json_encode($resetDetail), 'token_hash'));
same("\xff\xd8", substr($resetPhotoResponse->body, 0, 2));
same(1, (int) $resetDb->query("SELECT COUNT(*) FROM audit_log WHERE event_type = 'vocero.photo_viewed'")->fetchColumn());
$resetDb->exec("CREATE TRIGGER photo_audit_fail BEFORE INSERT ON audit_log WHEN NEW.event_type = 'vocero.photo_viewed' BEGIN SELECT RAISE(ABORT, 'synthetic audit failure'); END");
same(500, $resetRouter->handle('GET', '/api/voceros/' . $resetId . '/photo', $resetServer)->status);
same(403, $resetRouter->handle('GET', '/api/voceros/' . $resetId . '/photo', array_replace($resetServer, ['REMOTE_ADDR' => 'bad']))->status);
foreach (['%2e%2e', '..', str_repeat('z', 32)] as $id) same(422, $resetRouter->handle('GET', '/api/voceros/' . $id . '/photo', $resetServer)->status);
Finados\Http::destroySession(); session_id(''); $_SESSION = [];
$resetAuth->login('reset@example.invalid', $resetNewPassword, '192.0.2.31');
session_write_close(); session_id(''); $_SESSION = [];
same(401, $resetRouter->handle('GET', '/api/voceros/' . $resetId . '/photo', $resetServer)->status);
Finados\Http::destroySession(); session_id(''); $_SESSION = [];
