CREATE TABLE IF NOT EXISTS campaign_actions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  public_id TEXT NOT NULL UNIQUE,
  starts_on TEXT NOT NULL,
  ends_on TEXT NOT NULL,
  front TEXT NOT NULL DEFAULT 'emocional',
  title TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  channel TEXT NOT NULL DEFAULT '',
  owner TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'propuesta',
  created_by_admin_id INTEGER NULL,
  archived_at TEXT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_campaign_actions_range ON campaign_actions (starts_on, ends_on);


INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0010101010101010101010101010101', '2026-10-01', '2026-10-02', 'venta', 'Balance de preventa y ajuste de pauta', 'Revisar en el Panel las entradas por noche y localidad. Mover la pauta hacia las noches con menos ventas (viernes 30 de octubre, lunes 2 y martes 3 de noviembre).', 'Pauta Meta · Panel', 'Pauta y datos', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0020202020202020202020202020202', '2026-10-02', '2026-10-02', 'emocional', 'Cierre de tramo: «Lo que viene es para recordar»', 'Pieza puente entre la revelación del cartel y el tramo de recuerdo. Anuncia que empieza la etapa de memorias, sin datos nuevos.', 'Reel + historias', 'Audiovisual', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0030303030303030303030303030303', '2026-10-03', '2026-10-05', 'emocional', 'Convocatoria «Cuéntanos tu mejor recuerdo de Finados»', 'Motor «Memorias que vuelven». Pedir recuerdos con foto o relato. Publicar solo los autorizados, con consentimiento y sin datos de menores.', 'Reel + historias + comentarios', 'Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0040404040404040404040404040404', '2026-10-04', '2026-10-07', 'shows', 'Recuerdo con música: Kjarkas y William Luna (sábado 31 de octubre)', 'Tono de nostalgia: la música que acompañó a las familias. Cada pieza emocional cierra invitando a esa noche y al enlace de entradas.', 'Reel + pauta WhatsApp', 'Audiovisual + Pauta', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0050505050505050505050505050505', '2026-10-05', '2026-10-11', 'venta', 'Empuje a las noches con menos ventas', 'Viernes 30 de octubre (Grupo Bodega y Pablo Noboa), lunes 2 (Cliver y su Grupo Coralí, Sonido Mazter, K’ramelo Latino) y martes 3 de noviembre (El Loco Abraham). Solo precios y localidades confirmados en Ticketstar.', 'Pauta Meta + redes', 'Pauta', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0060606060606060606060606060606', '2026-10-06', '2026-10-09', 'atractivos', 'La tradición que se vive: colada morada y guaguas de pan', 'Recuerdo de la tradición familiar llevado a lo que se vive en la feria: gastronomía, +500 stands y la elección de Rey Pan y Señorita Colada Morada.', 'Carrusel + historias', 'Diseño + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0070707070707070707070707070707', '2026-10-07', '2026-10-07', 'medios', 'Gira de medios: historias de recuerdo', 'Voceros y emprendedores cuentan su recuerdo de Finados en radio y TV. Coordinar desde Medios → Gira de medios.', 'Radio + TV', 'Comunicación', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0080808080808080808080808080808', '2026-10-08', '2026-10-10', 'shows', 'Guaynaa, Waldokinc y Golpe a Golpe (domingo 1 de noviembre)', 'La generación que vuelve a casa para el feriado. Recuerdo + plan con amigos. Incluir a Las Ñañas en la Plaza de la Luna ese mismo día.', 'Reel + TikTok + pauta', 'Audiovisual + Pauta', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0090909090909090909090909090909', '2026-10-09', '2026-10-11', 'participacion', 'Voceros: video «Mi recuerdo de Finados»', 'Pedir a los voceros un video corto con su recuerdo y la invitación a la feria. Revisar y validar views en Voceros.', 'TikTok + Instagram de voceros', 'Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0101010101010101010101010101010', '2026-10-12', '2026-10-15', 'emocional', '«Mi familia es tradición»', 'Motor «Familias que comparten». Foto o recuerdo familiar para selección por jurado. Participar, publicar y pautar requieren consentimientos separados.', 'Reel + historias', 'Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0111111111111111111111111111111', '2026-10-13', '2026-10-18', 'atractivos', 'Ruta familiar: qué hacer además de los shows', 'Dinosaurios, show de alta escuela, juegos mecánicos, resbaladera gigante y granja turística. Un atractivo por pieza, con horario y ubicación confirmados.', 'Carrusel + Reels', 'Diseño + Audiovisual', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0121212121212121212121212121212', '2026-10-14', '2026-10-20', 'shows', 'Plaza de la Luna: Las Ñañas (1 de noviembre) y Hueveando (3 de noviembre)', 'Experiencia cultural con legado y tradición. Comunicar solo la programación aprobada por la Plaza de la Luna.', 'Reel + carrusel', 'Audiovisual', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0131313131313131313131313131313', '2026-10-16', '2026-10-22', 'participacion', 'Mushuc Freestyle: inscripciones abiertas', 'Invitar a MC a inscribirse antes del jueves 29 de octubre a las 23:59. Final el lunes 2 de noviembre a las 13:00 en la Plaza de la Luna.', 'TikTok + Instagram + comunidades', 'Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0141414141414141414141414141414', '2026-10-19', '2026-10-25', 'participacion', 'De emprendedor a influencer: historias de expositores', 'Cada expositor cuenta su historia, producto y ubicación. Coordinar desde Emprendedores.', 'Reels de expositores', 'Community + Comercial', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0151515151515151515151515151515', '2026-10-12', '2026-10-25', 'venta', 'Elige tu noche en familia', 'Qué noche y qué localidad conviene a cada plan (familia, amigos, pareja). Solo condiciones confirmadas en Ticketstar.', 'Pauta Meta + web SHOWS', 'Pauta + Comercial', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0161616161616161616161616161616', '2026-10-20', '2026-10-25', 'medios', 'Conversaciones ES TRADICIÓN en vivo', 'Serie de lives de 20–30 minutos con talento local, emprendedores y visitantes frecuentes. Requiere invitados confirmados, moderación y CTA.', 'Facebook Live + Instagram Live', 'Comunicación + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0171717171717171717171717171717', '2026-10-26', '2026-10-30', 'shows', 'Cuenta regresiva: un día, una noche', 'Cada día una noche del cartel con su artista principal, hora y enlace directo de compra.', 'Reels + historias + pauta', 'Audiovisual + Pauta', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0181818181818181818181818181818', '2026-10-26', '2026-10-29', 'servicio', 'Cómo llegar: accesos, parqueaderos, horarios y mapa', 'Información de servicio para la visita. Solo datos validados por Operación.', 'Carrusel + historias + web', 'Diseño + Operación', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0191919191919191919191919191919', '2026-10-27', '2026-10-29', 'participacion', 'Último llamado Mushuc Freestyle', 'Cierre de inscripciones el jueves 29 de octubre a las 23:59.', 'Historias + TikTok', 'Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0202020202020202020202020202020', '2026-10-28', '2026-10-30', 'medios', 'En vivo desde el montaje', 'Transmisiones cortas del montaje y preparación, sin mostrar contratos, camerinos ni zonas restringidas.', 'Lives + historias', 'Comunicación', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0212121212121212121212121212121', '2026-10-26', '2026-10-30', 'venta', 'Últimas entradas por localidad', 'Comunicar disponibilidad solo con inventario real de Ticketstar. Nada de «agotado» si no está conciliado.', 'Pauta Meta + WhatsApp', 'Pauta + Datos', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0222222222222222222222222222222', '2026-10-29', '2026-10-30', 'atractivos', 'Rey Pan y Señorita Colada Morada: último llamado', 'Invitar a votar y a vivir la tradición en la feria.', 'Historias + publicación', 'Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0232323232323232323232323232323', '2026-10-30', '2026-10-30', 'shows', 'Viernes 30: Grupo Bodega y Pablo Noboa', 'Cobertura en vivo de la primera noche: llegada, ambiente y show.', 'Historias + Reels en vivo', 'Audiovisual + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0242424242424242424242424242424', '2026-10-31', '2026-10-31', 'shows', 'Sábado 31: William Luna, Kjarkas y Encuentro Sur', 'Cobertura en vivo y clips para el recuerdo.', 'Historias + Reels en vivo', 'Audiovisual + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0252525252525252525252525252525', '2026-11-01', '2026-11-01', 'shows', 'Domingo 1: Guaynaa, Waldokinc y Golpe a Golpe · Las Ñañas en la Plaza de la Luna', 'Cobertura en vivo del día de mayor convocatoria.', 'Historias + Reels en vivo', 'Audiovisual + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0262626262626262626262626262626', '2026-11-02', '2026-11-02', 'atractivos', 'Final Mushuc Freestyle (13:00, Plaza de la Luna)', 'Cobertura de la final y premiación. En la noche: Cliver y su Grupo Coralí, Sonido Mazter y K’ramelo Latino.', 'Historias + Reels', 'Audiovisual + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0272727272727272727272727272727', '2026-11-03', '2026-11-03', 'shows', 'Martes 3: El Loco Abraham · Hueveando en la Plaza de la Luna', 'Cobertura del cierre.', 'Historias + Reels en vivo', 'Audiovisual + Community', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0282828282828282828282828282828', '2026-10-31', '2026-11-03', 'servicio', 'Servicio en vivo', 'Avisos de accesos, filas, clima y objetos perdidos. Respuesta rápida en comentarios y mensajes.', 'Historias + mensajes', 'Community + Operación', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO campaign_actions (public_id, starts_on, ends_on, front, title, detail, channel, owner, status, created_at, updated_at) VALUES ('a0292929292929292929292929292929', '2026-11-03', '2026-11-03', 'emocional', '«Gracias por volver»', 'Cierre emocional de la edición con los recuerdos de estos días, autorizados.', 'Reel + publicación', 'Audiovisual', 'propuesta', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO schema_migrations (version, applied_at) VALUES ('035_campaign_actions', CURRENT_TIMESTAMP);
